// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLCdnY6BVisdIk-CHYk7OnuMGPH7RD1EI',
    appId: '1:273067128695:web:41031d859b4bfd59f45372',
    messagingSenderId: '273067128695',
    projectId: 'peony-project',
    authDomain: 'peony-project.firebaseapp.com',
    storageBucket: 'peony-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8xCY7t-KnrMSFQQ7snLrq58pE6sYn0NY',
    appId: '1:273067128695:android:108223f72d17ede3f45372',
    messagingSenderId: '273067128695',
    projectId: 'peony-project',
    storageBucket: 'peony-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBEwwYLdGAu6a0kH2QlvOSEv4knmtqso4',
    appId: '1:273067128695:ios:9d2f30ef9b3848d4f45372',
    messagingSenderId: '273067128695',
    projectId: 'peony-project',
    storageBucket: 'peony-project.appspot.com',
    iosClientId: '273067128695-nvgsrhl9bmjji6uq2mpptiad46nc1q2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.peonyProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBEwwYLdGAu6a0kH2QlvOSEv4knmtqso4',
    appId: '1:273067128695:ios:9d2f30ef9b3848d4f45372',
    messagingSenderId: '273067128695',
    projectId: 'peony-project',
    storageBucket: 'peony-project.appspot.com',
    iosClientId: '273067128695-nvgsrhl9bmjji6uq2mpptiad46nc1q2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.peonyProject',
  );
}
